LizardByte/ThemerrDB

- .github/ISSUE_TEMPLATE/add-game-theme.yml
- .github/ISSUE_TEMPLATE/add-movie-theme.yml
> update issue template forms

- issue_updater.py
- fix args for `issue_updater.py`
> fix args for `issue_updater.py`

- issue_updater.py
- strip whitespace from issue input fields
> strip whitespace from issue input fields

- .github/workflows/auto-update-db.yml
- .github/workflows/update-pages.yml
- gh-pages-template/games/igdb/1638.json
- gh-pages-template/movies/imdb/0084787.json
- gh-pages-template/movies/imdb/0113189.json
- gh-pages-template/movies/themoviedb/1091.json
- gh-pages-template/movies/themoviedb/710.json
- gh-pages-template/movies/thetvdb/515.json
- gh-pages-template/movies/thetvdb/765.json
- issue_updater.py
- use database branch
- gh-pages branch should properly update on a schedule following this change
- issue_updater now runs from code in master branch, and updates the files in the database branch
> use database branch

- .github/workflows/auto-update-db.yml
- rename workflow job
- fix working directory for `submission.json`
- file not found after [e5989d2f74ac422504eb999aa5d1ba9946e9d575](https://github.com/LizardByte/ThemerrDB/commit/e5989d2f74ac422504eb999aa5d1ba9946e9d575)
> fix working directory for `submission.json`

- issue_updater.py
> prepend imdb id with `tt`

- issue_updater.py
> fix imdb id prefix

- issue_updater.py
> fix imdb id comparison

- .github/ISSUE_TEMPLATE/add-movie-theme.yml
- .github/workflows/auto-update-db.yml
- .github/workflows/python-tests.yml
- .github/workflows/update-pages.yml
- README.md
- issue_updater.py
- requirements.txt
- tests/conftest.py
- tests/unit/test_issue_updater.py
- simplifies adding/updating movies
- more data provided, which will aid in creation of a web ui
- tvdb will be removed (no cross-reference in tmdb)
- imdb will remain (cross-reference exists in tmdb)
- change python execution to unbuffered mode (test if output is printed in GitHub workflow UI before python execution is finished)
Todo:
> exclusively use tmdb api for movies

- .github/workflows/update-pages.yml
Fixes checkout for `database` branch for daily update action.
> fix database checkout for daily update

- .gitignore
- gh-pages-template/index.html
- gh-pages-template/js/item_loader.js
- updater.py
This is the initial website. Still some work to do, but will probably be a separate PR. This also adds an `all.json` file to igdb and themoviedb directories.
Todo:
> initial website

- gh-pages-template/js/item_loader.js
Adjust the layout of item card on the website.
> adjust website card layout

- gh-pages-template/index.html
- gh-pages-template/js/item_loader.js
- gh-pages-template/js/yt.js
Adds a YouTube audio player to each item on the website.
> add yt player

- gh-pages-template/index.html
- gh-pages-template/js/item_loader.js
- gh-pages-template/js/yt.js
This pr improves performance of the youtube player on the website, by creating a single player instance. Additionally, a progress bar has been added. The player is fixed to the bottom of the webpage.
> optimize yt player

- gh-pages-template/js/item_loader.js
Fix broken links for tmdb items.
> website: fix tmdb links

- updater.py
> issues: fix precheck arguments

- .github/workflows/auto-update-db.yml
Fix update issue title step env variables.
> issues: fix update issue title env

- .github/workflows/auto-update-db.yml
> issues: fix github outputs

- .github/workflows/auto-update-db.yml
- updater.py
issues: fix issue comment format
> issues: fix issue comment format

- .github/workflows/auto-update-db.yml
issues: fix diff comment directory
> issues: fix diff comment directory

- .github/workflows/auto-update-db.yml
> issues: fix git diff command

- .github/workflows/auto-update-db.yml
- updater.py
Automate contributor stats.
For the item added:
- youtube_theme_added: timestamp
- youtube_theme_edited: timestamp
- youtube_theme_added_by: user_id
- youtube_theme_edited_by: user_id
`contributors.json`
- items_added: increment by one when adding a new item
- items_edits: increment by one by editing an existing item
> database: automate contributor stats

- gh-pages-template/js/item_loader.js
This PR fixes a bug where items would not be sorted alphabetically, due to the speed of the second ajax request. The item container is now created before the second ajax request to eliminate this issue.
> website: fix sort order

- gh-pages-template/js/item_loader.js
Move edit button below item summary.
> website: move edit button

- gh-pages-template/js/item_loader.js
Move card footer row to bottom of item card by replacing `d-table` with `d-flex`.
> website: move card footer row to bottom of card

- tests/unit/test_issue_updater.py
- updater.py
Use common functions for games and movies processing to eliminate duplicated code fragments.
> updater: refactor games and movies processing

- gh-pages-template/js/item_loader.js
- updater.py
This PR moves some files around in the database.
- `contributors.json` is moved up one level.
- `all.json` is now removed.
- `pages.json` is added which includes the total number of pages.
- `all_page_X.json` is added, where `X` is the page number, starting at 1.
The website will now utilize the pages as well. The website will load one page at a time and load the next page upon scrolling a `load more` button into view.
> database: implement pages

- gh-pages-template/js/item_loader.js
- Fixes loading pages too quickly by adding a 0.1 second timeout.
- Also fixes a bug where the final page would not load.
> website: fix rapid page loading

- gh-pages-template/index.html
- gh-pages-template/js/item_loader.js
This PR adds a search function to the website. Since some of these existing code was utilized to populate the results, this has been moved to a separate function.
This uses levenshtein distance to determine if an item matches. A better algorithm should probably be used in the future.
> website: add search

- updater.py
When `process_tmdb_id` and `process_igdb_id` methods were combined into `process_item_id`, the issue title was left with the game method for both movie and game conditions. This PR adds it back into the game or movie specific logic.
> updater: fix issue title for movies

- gh-pages-template/index.html
- gh-pages-template/js/item_loader.js
This PR adds the `overflow-hidden` class to the `main` html object which fixes the issue present on mobile devices with narrow screens. Essentially, the navbars are now fixed.
Additionally, levenshtein_distance and ranking_sorter are now downloaded from the main website. No reason to duplicate code between repos.
> website: fix overflow and use common js

- .github/workflows/auto-update-db.yml
Adds workflow queue and label protection (i.e. ensure the label adding actor is a public org member)
> ci: database: add workflow queue and label protection

- .github/workflows/auto-update-db.yml
Using GitHub CLI in a GitHub Actions workflow requires the env to be setup like this.
> ci: database: update env

- updater.py
Add `exception_writer` method to allow handling exceptions for igdb and themoviedb urls.
> database: check for invalid urls

- .github/workflows/update-pages.yml
- .gitignore
- README.md
- package.json
- requirements.txt
- updater.py
Add plots of each item type in the database showing db growth over time.
> database: plot db growth

- updater.py
Fix issue where repeated date added would only increment total count by one.
> database: fix growth graphs

- README.md
Update graph urls to point to published GH pages url instead of raw file in database branch, since it wasn't updating correctly.
> readme: update graph urls

- updater.py
If the last entry in the graph is not today's date, we will add another entry with no increase to item count.
> database: fix final entry in graph

- requirements.txt
- updater.py
This PR replaces `youtube-dl` with `yt-dlp`.
`youtube-dl` is either incapable or unwilling to publish a new release since this (https://github.com/ytdl-org/youtube-dl/issues/31530) breaking issue was introduced. While they have "fixed" the issue in source, no release has been made. Several messages/comments by myself and many others have offered to assist the maintainers in finalizing CI so they can automate releases but these messages are either ignored or responses indicated there will be a new release "soon".
ℹ️ These comments and not meant to criticize the youtube-dl project or its maintainers. They are just to provide context for the decision to switch to yt-dlp.
must …
> build(deps): replace youtube-dl with yt-dlp

- .github/workflows/auto-update-db.yml
- updater.py
Add labels to issues and prevent items with exceptions from being added.
> issues: label exceptions

- updater.py
- Fixes potential issues in requests loop, discovered in PluggerDB (https://github.com/LizardByte/PluggerDB/pull/21, https://github.com/LizardByte/PluggerDB/pull/331, and https://github.com/LizardByte/PluggerDB/pull/346).
> updater: improve requests loop

- updater.py
Fixes an issue where if a contributors first contribution is an edit, it would count as an addition instead of an edit.
> fix(contributors): fix editor counter

- gh-pages-template/index.html
- tests/unit/test_issue_updater.py
- updater.py
- Sanitize YouTube url in test.
- Ensure "Movie" is pre-selected in website search.
- Remove clean files section of `updater.py`
- Fixes https://github.com/LizardByte/ThemerrDB/security/code-scanning/1
> fix(test): sanitize youtube url

- .github/workflows/auto-update-db.yml
Adds a method to use an approval queue using labels.
> ci: add approval queue

- README.md
- updater.py
This PR adds a total item count that can be consumed by the badges. Additionally, the badges link to "anchors" in the markdown.
Also, fixes the issue with the relative youtube instructions page not working within the quote `>` block.
> docs: add badges and fix youtube link

- .github/workflows/auto-update-db.yml
- .github/workflows/python-tests.yml
- .github/workflows/update-pages.yml
- README.md
- codecov.yml
- requirements-dev.txt
- src/updater.py
- tests/unit/test_issue_updater.py
> ci: add code coverage

- README.md
Add last updated badges for `database` and `gh-pages` branches.
Add badges for under review and approved themes.
> docs: add last updated badges

- .github/workflows/auto-update-db.yml
Fixes issue where the wrong label was removed from completed items.
> ci: fix label removal

- .github/workflows/python-tests.yml
- README.md
- src/updater.py
- tests/conftest.py
- tests/unit/test_issue_updater.py
Add IMDB count and restyle database count badges
> docs: add imdb count and re-style badges

- src/updater.py
Add `imdb_id` to page files to allow easier caching a list of imdb ids available in our database.
> feat: add imdb id to page files

- .github/workflows/python-tests.yml
- .github/workflows/update-pages.yml
This PR adds internal and external environments for PR events.
Todo:
> ci: add internal and external environments for PRs

- .github/workflows/python-tests.yml
- .github/workflows/update-pages.yml
Reverts LizardByte/ThemerrDB#2038
> Revert "ci: add internal and external environments for PRs"

- docs/Theme_Guidelines.md
Added guideline for no themes from opening sequences
Added a guideline for themes to not be from opening sequences.
> Add Theme Guideline

- docs/Theme_Guidelines.md
Fix typo in docs and add emphasis to `NOT`.
> docs: fix typo in theme guidelines

- .github/workflows/update-pages.yml
The conditional check for the update step did not allow the step to run for daily updates.
> fix: conditional check for daily update workflow

- README.md
> docs(readme): add Themerr-kodi

- .gitignore
- src/updater.py
- tests/conftest.py
- tests/unit/test_issue_updater.py
This change adds some basic validation around the issue body.
> fix: validate submission headings

- tests/unit/test_issue_updater.py
> tests: parametrize unit tests

- .github/workflows/python-tests.yml
- Update coverage on push events.
- Remove `nightly` branch from PR events.
> tests: update coverage on push events

- .github/workflows/Relabel_issue.yml
Minor bug fixes extending #2581 
> fix: use correct params for add/remove labels

- .github/workflows/Relabel_issue.yml
> fix: more fixes for relabel workflow

- .github/workflows/auto-update-db.yml
There is a small chance the `approve-theme` label could be removed while the workflow is running. If this happens, we will not continue with the commit/push, or closing the issue.
> fix: check for possible removal of approve-theme label

- docs/YouTube_Share.md
Remove the warning about using playlist from the docs.
> docs: remove playlist warning

- .github/workflows/Comment_command.yml
- .github/workflows/auto-update-db.yml
- bot_commands.md
This PR adds initial support for comment commands by moderators.
- `@LizardByte-bot approve` approve the theme
- `@LizardByte-bot edit {youtube_url}` replace the YouTube url in the issue body with the given url
> feat: add comment commands

- .github/workflows/Comment_command.yml
- .github/workflows/auto-update-db.yml
> fix: comment command syntax and permission fixes

- .github/workflows/Comment_command.yml
- Add context dump
- Add console logging
- Try to fix comment issue id
- Try to fix regex
> fix: add issue comment context debugging and logging

- .github/workflows/Comment_command.yml
- Fix regex pattern
- Regex is now case-insensitive, global, and multiline
- comment id should now be passed in correctly
> fix: more command comment fixes

- .github/workflows/Comment_command.yml
Fix undefined variable `issue_body`.
> fix: correct undefined variable

- src/updater.py
- tests/conftest.py
Better handling of playlist URLs and exiting script. Script is now exited with 0 exit code to allow remaining workflow steps to complete.
> fix(issues): better handling of playlist urls

- .github/ISSUE_TEMPLATE/theme.yml
Add tv show example to theme issue template, and re-order examples.
> fix(issues): add tv show example to template

- .github/ISSUE_TEMPLATE/theme.yml
Update theme request template.
> feat(template): add replacement reason field

- src/updater.py
- tests/conftest.py
- tests/unit/test_issue_updater.py
When an exception occurred the issue was marked as a duplicate and immediately closed. This should fix that.
> fix(issue-updated): return early if no youtube url found

- .github/workflows/auto-update-db.yml
Use env variable to prevent script injection. This should also solve the issue when a single quote was present in json data.
> fix(submission): prevent script injection

- src/updater.py
Follow up fix for https://github.com/LizardByte/ThemerrDB/pull/4250
> fix(requests): do not auto close if youtube url is invalid

- docs/Approver_Guide.md
> Add regional block website to tools

- .github/workflows/update-pages.yml
Artifacts are failing to upload due to file counts, so archive them into one file before uploading.
> fix: archive artifacts before upload

- .github/workflows/python-tests.yml
Use colored output for pytest.
> ci(pytest): add colored output

- README.md
Added a note about pausing submissions
> Pause submissions

- gh-pages-template/index.html
> fix(locale): update crowdin url
