.github/workflows/auto-update-db.yml, updater.py
Add prechecks to issues/requests. This should do the following:
- Update the issue title automatically based on the found metadata of the item
- Add a comment to the issue with metadata about the item as well as the diff of what would change.
Unable to test until this is in `master` branch.
=> issues: add prechecks

.gitignore, updater.py
Fixes comment file append. YouTube url is processed first, so this should be in write mode, while the game/movie is processed next so those should be in append mode.
Additionally, fixes an issue with the igdb poster image in the comment.
=> issues: fix comment file append

updater.py
- issue comment formatting was inadvertently broken by a re-indent
- format json files with 4 indents, except `all.json`
=> formatting: fix various format issues

.github/workflows/auto-update-db.yml
Add workflow concurrency. This will act as a queue. The concurrency group is based on the label added.
=> ci: add workflow concurrency

.github/workflows/auto-update-db.yml
Cannot use concurrency since it still cancels pending jobs.
=> database: remove workflow concurrency

updater.py
Replace `\n` with `<br>` in item summaries within the markdown table.
=> issues: support line breaks in markdown tables

.github/workflows/auto-update-db.yml
Close and lock issue using GitHub cli instead of actions.
- Replaces #1011 
=> ci(auto-update-db): close and lock issue with github cli

updater.py
Fix poster url when poster url is empty.
=> fix(issues): fix poster url when no poster

updater.py
Removes space in plot file names, which will fix an issue with the readme. This will also remove the existing files on the next update.
=> fix(plots): remove space in plot filenames

.github/workflows/update-pages.yml
=> ci: do not allow force push

.github/workflows/update-pages.yml
This PR removes `nightly` branch from the pull request event.
=> ci: remove nightly branch event

src/updater.py
In rare situations a summary may contain a classic macOS line ending (`\r`) instead of `\n`.
=> fix: replace macos line endings with html break

.github/workflows/update-pages.yml, src/updater.py, tests/conftest.py, tests/unit/test_issue_updater.py
Allow skipping tests that require secrets. This is a temporary fix, but ideally we would like a way to provide our secrets to fork external PRs.
=> tests: allow skipping tests that require secrets

src/updater.py, tests/unit/test_issue_updater.py
Allow YouTube URL in issue body to be a playlist.
Todo:
=> feat: allow playlist urls

.github/workflows/Relabel_issue.yml
This PR adds a new workflow which will run when issues are edited. The workflow will do the following.
- Remove `approve-queue` and/or `approve-theme` labels.
- Remove `request-theme` label and re-apply it... thus re-running the initial check.
=> feat: automatically re-label edited issues

.github/workflows/Relabel_issue.yml
- Automatically remove `question` label when an issue is edited.
- Add an `edited` label when an issue is edited.
=> feat: remove question label and add edited label on issue edit

.github/workflows/Relabel_issue.yml
When an issue is created without a title, the bot would edit the title... thus triggering the labels to re-applied. This PR will check if the edits were made by the bot, and skip them if the workflow if they were.
=> fix: skip relabel on edits by bot

.github/workflows/Comment_command.yml
- re-apply request label on comment command edits in order to trigger new workflow run
- fix undeclared variable issue on approve command
- reduce number of api calls to add `approve-queue` and `approve-theme` labels
- only edit issue if body actually changes
=> fix: re-apply request label on comment command edit

README.md, src/updater.py, tests/conftest.py, tests/unit/test_issue_updater.py
This PR adds initial support for TV Shows using TheMovieDB as a source db.
=> feat(db): add tv show support

.github/workflows/auto-update-db.yml, .gitignore, src/updater.py, tests/unit/test_issue_updater.py
- Auto close exact duplicates
- Label duplicates where the theme changes
- Fix small bug where request retry count was off by one
- Use a single api request to set and remove the labels
=> feat: handle duplicate submissions

.github/workflows/auto-update-db.yml
argument should be "not planned", not "not_planned"
```txt
invalid argument "not_planned" for "-r, --reason" flag: valid values are {completed|not planned}
Usage:  gh issue close {<number> | <url>} [flags]
Flags:
-c, --comment string   Leave a closing comment
-r, --reason string    Reason for closing: {completed|not planned}
```
=> fix(auto_close): use correct argument for close reason

src/updater.py
https://github.com/LizardByte/ThemerrDB/pull/4250 was not a proper fix. Hopefully this one will be better.
Current situation:
Update step:
```txt
[youtube] Extracting URL: https://www.youtube.com/watch?v=fM-_T6jXS7U
[youtube] fM-_T6jXS7U: Downloading webpage
[youtube] fM-_T6jXS7U: Downloading ios player API JSON
ERROR: [youtube] fM-_T6jXS7U: Video unavailable. This video contains content from NBC Universal, who has blocked it in your country on copyright grounds
Error processing youtube: ERROR: [youtube] fM-_T6jXS7U: Video unavailable. This video contains content from NBC Universal, who has blocked it in your country on copyright grounds
Error processing youtube: Error processing YouTube url
```
Git diff step:
```txt
cat: ../title.md: No such file or directory
Error: Process completed …
```
=> fix(request): process item url unconditionally

README.md, docs/Approver_Guide.md, docs/Theme_Guidelines.md
GitHub changed the admonitions. See https://github.com/orgs/community/discussions/16925
=> docs: fix admonitions
